### ISSUE TITLE
启动bot报错 TypeError: _evaluate() missing 1 required positional argument: 'recursive_guard'

### ISSUE THREAD

**Issue by MeIsNewCoder** [ssttkkl/PixivBot#11]
运行 python bot.py 时报错 TypeError: _evaluate() missing 1 required positional argument: 'recursive_guard'

控制台完整日志

````
root@unraid:/mnt/user/public/mirai/PixivBot# python3 bot.py 
Traceback (most recent call last):
  File "/mnt/user/public/mirai/PixivBot/bot.py", line 4, in <module>
    from graia.application import GraiaMiraiApplication, Session
  File "/usr/lib64/python3.9/site-packages/graia/application/__init__.py", line 26, in <module>
    from .message.elements.internal import Image, Source, Voice
  File "/usr/lib64/python3.9/site-packages/graia/application/message/elements/internal.py", line 598, in <module>
    Quote.update_forward_refs(MessageChain=MessageChain)
  File "/usr/lib64/python3.9/site-packages/pydantic/main.py", line 677, in update_forward_refs
    update_field_forward_refs(f, globalns=globalns, localns=localns)
  File "/usr/lib64/python3.9/site-packages/pydantic/typing.py", line 233, in update_field_forward_refs
    field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
  File "/usr/lib64/python3.9/site-packages/pydantic/typing.py", line 50, in evaluate_forwardref
    return type_._evaluate(globalns, localns)
TypeError: _evaluate() missing 1 required positional argument: 'recursive_guard'
````
依赖
````
Package                 Version
----------------------- ----------
aiofiles                0.5.0
aiohttp                 3.7.3
async-timeout           3.0.1
attrs                   20.3.0
certifi                 2020.11.8
chardet                 3.0.4
cloudscraper            1.2.48
croniter                0.3.36
ez-setup                0.9
graia-application-mirai 0.8.4
graia-broadcast         0.5.0
graia-template          0.0.4
idna                    2.10
iterwrapper             0.1.4
json5                   0.9.5
loguru                  0.5.1
multidict               5.0.2
natsort                 7.1.0
Pillow                  8.0.0
pip                     20.2.4
PixivPy                 3.5.10
pydantic                1.6.1
pyparsing               2.4.7
PySocks                 1.7.1
python-dateutil         2.8.1
regex                   2020.11.13
requests                2.25.0
requests-toolbelt       0.9.1
setuptools              50.3.2
six                     1.15.0
typing-extensions       3.7.4.3
urllib3                 1.26.2
yarl                    1.6.3
````

**Comment by MeIsNewCoder** [comment]
https://github.com/aiogram/aiogram/issues/437

**Comment by MeIsNewCoder** [comment]
python 版本降级到3.8.6后正常运行
