### ISSUE TITLE
bot 启动报错 TypeError: Cannot create a consistent method resolution

### ISSUE THREAD

**Issue by wingxia** [ssttkkl/PixivBot#16]
```
`Traceback (most recent call last):
  File "bot.py", line 3, in <module>
    from graia.application import GraiaMiraiApplication, Session
  File "/qqbot/PixivBot/pixiv_venv/lib/python3.7/site-packages/graia/application/__init__.py", line 17, in <module>
    from graia.application.event.lifecycle import (  # for init lifecycle events
  File "/qqbot/PixivBot/pixiv_venv/lib/python3.7/site-packages/graia/application/event/lifecycle.py", line 6, in <module>
    class ApplicationLaunched(BaseModel, BaseEvent):
  File "/qqbot/PixivBot/pixiv_venv/lib/python3.7/site-packages/graia/broadcast/entities/event.py", line 27, in __new__
    **kwargs
  File "pydantic/main.py", line 324, in pydantic.main.ModelMetaclass.__new__
  File "/www/server/panel/pyenv/lib/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases BaseModel, BaseEvent
`
```

**Comment by ssttkkl** [comment]
已修复，请更新后重新安装依赖
