### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by sakurayun** [ssttkkl/PixivBot#18]
报错如下：
```
C:\Users\Administrator\Desktop\pixivbot\PixivBot0.2.1>python bot.py
2021-02-16 05:02:35.264 | INFO     | utils.settings:<module>:38 - Config file was loaded successfully.
Traceback (most recent call last):
  File "bot.py", line 28, in <module>
    HelpQueryHandler(tag="help query",settings=settings["help"]),
  File "C:\Users\Administrator\Desktop\pixivbot\PixivBot-0.2.1\handler\help_quer
y_handler.py", line 14, in __init__
    self.text = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x9c in position 10: illegal multibyte sequence
```
请问该如何解决？

**Comment by h2dyn** [comment]
在PixivBot-0.2.1\handler\help_quer
y_handler.py里面把with open(self.text_file, "r") as f:改成with open(self.text_file, "r",encoding='utf-8') as f:

**Comment by sakurayun** [comment]
太难了....
```
Traceback (most recent call last):
  File "bot.py", line 83, in <module>
    app.launch_blocking()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\graia\application\__init__.py", line 1578, in launch_blocking
    loop.run_until_complete(self.initialize())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asynci
o\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\graia\application\__init__.py", line 1468, in initialize
    await self.authenticate()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\graia\application\utilles.py", line 27, in wrapper
    return await func(self, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\graia\application\__init__.py", line 308, in authenticate
    response.raise_for_status()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\aiohttp\client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 404, message='Not Found', url=URL
('http://127.0.0.1:8080/auth/')
```
