### ISSUE TITLE
启动出错

### ISSUE THREAD

**Issue by tamako-1** [ssttkkl/PixivBot#22]
Traceback (most recent call last):
  File "H:\mirai\PixivBot-0.2.1\pixiv\pixiv_api.py", line 35, in watchman
    await launch(auth)
  File "H:\python\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "H:\mirai\PixivBot-0.2.1\pixiv\pixiv_api.py", line 27, in auth
    papi.login(settings["pixiv"]["username"], settings["pixiv"]["password"])
  File "H:\python\lib\site-packages\pixivpy3\api.py", line 75, in login
    return self.auth(username=username, password=password)
  File "H:\python\lib\site-packages\pixivpy3\api.py", line 114, in auth
    raise PixivError(
pixivpy3.utils.PixivError: [ERROR] auth() failed! check username and password.
HTTP 400: {"has_error":true,"errors":{"system":{"message":"Invalid grant_type parameter or parameter missing","code":1508}},"error":"invalid_grant"}
启动bot.py时出现错误

**Comment by Midolii** [comment]
遇到了同样的错误
