### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by wayne0926** [ssttkkl/PixivBot#41]
非`docker`版本，我把[nonebot-plugin-pixivbot-onebot-v11](https://github.com/ssttkkl/nonebot-plugin-pixivbot-onebot-v11) `src`文件夹直接放进了插件文件夹
```
08-07 12:21:35 [INFO] nonebot | Current Env: prod
08-07 12:21:35 [ERROR] nonebot | Failed to import "nonebot_plugin_pixivbot_onebot_v11"
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/pm-DFMY191v-py3.9/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/root/.cache/pypoetry/virtualenvs/pm-DFMY191v-py3.9/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/pm-DFMY191v-py3.9/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/pm-DFMY191v-py3.9/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.cache/pypoetry/virtualenvs/pm-DFMY191v-py3.9/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/pm-DFMY191v-py3.9/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/pm-DFMY191v-py3.9/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/root/.cache/pypoetry/virtualenvs/pm-DFMY191v-py3.9/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/www/wwwroot/pm/Nonebot2/./bot.py", line 26, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/root/.cache/pypoetry/virtualenvs/pm-DFMY191v-py3.9/lib/python3.9/site-packages/nonebot/plugin/load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/.cache/pypoetry/virtualenvs/pm-DFMY191v-py3.9/lib/python3.9/site-packages/nonebot/plugin/load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/pm-DFMY191v-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 172, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/pm-DFMY191v-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/pm-DFMY191v-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 148, in load_plugin
    module = importlib.import_module(
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/pm-DFMY191v-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/www/wwwroot/pm/Nonebot2/./nonebot2/plugins/nonebot_plugin_pixivbot_onebot_v11/__init__.py", line 10, in <module>
    from .protocol_dep.authenticator import Authenticator
  File "/www/wwwroot/pm/Nonebot2/./nonebot2/plugins/nonebot_plugin_pixivbot_onebot_v11/protocol_dep/authenticator.py", line 1, in <module>
    from nonebot_plugin_pixivbot import context
ModuleNotFoundError: No module named 'nonebot_plugin_pixivbot'
```

**Comment by ssttkkl** [comment]
请用pip install 方式安装，或者把[nonebot_plugin_pixivbot](https://github.com/ssttkkl/nonebot-plugin-pixivbot)也放到src目录（nonebot_plugin_pixivbot_onebot_v11依赖nonebot_plugin_pixivbot）
