### ISSUE TITLE
运行 bot.py 时报错 ModuleNotFoundError: No module named 'graia.template'

### ISSUE THREAD

**Issue by mtuba** [ssttkkl/PixivBot#8]
**我的思路**
按照 README 给出的使用方式运行

**我的问题**
运行 `python3 bot.py` 时报错 ModuleNotFoundError: No module named 'graia.template'

**完整控制台输出**

```
root@VM-0-12-ubuntu:~/PixivBot/PixivBot-0.2.0# pip3 install -r requirements.txt
Collecting PixivPy (from -r requirements.txt (line 1))
  Downloading http://mirrors.tencentyun.com/pypi/packages/90/e2/20909e1048eade0b1ab2f2f4e792b3c841142d5b36d7d83da09e8c327046/PixivPy-3.5.10-py3-none-any.whl
Collecting graia-application-mirai (from -r requirements.txt (line 2))
  Downloading http://mirrors.tencentyun.com/pypi/packages/55/db/efff8c5fb88a1b2ee3e14dff860cb2d7e3e90ae3aad5ad69f86132110930/graia_application_mirai-0.10.10-py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 641kB/s 
Collecting json5 (from -r requirements.txt (line 3))
  Downloading http://mirrors.tencentyun.com/pypi/packages/2b/81/22bf51a5bc60dde18bb6164fd597f18ee683de8670e141364d9c432dd3cf/json5-0.9.5-py2.py3-none-any.whl
Collecting Pillow (from -r requirements.txt (line 4))
  Downloading http://mirrors.tencentyun.com/pypi/packages/00/08/aa5071a3c552c0f53107b618a8828aaa1fff2e25bca37bcae27a2e688d38/Pillow-8.0.1-cp38-cp38-manylinux1_x86_64.whl (2.2MB)
    100% |████████████████████████████████| 2.2MB 45.5MB/s 
Collecting aiofiles (from -r requirements.txt (line 5))
  Downloading http://mirrors.tencentyun.com/pypi/packages/77/47/19e5951cc6ed771669906d2946b3deac32a35a9a155f730be49d8fa73dc9/aiofiles-0.6.0.tar.gz
Collecting loguru (from -r requirements.txt (line 6))
  Downloading http://mirrors.tencentyun.com/pypi/packages/6d/48/0a7d5847e3de329f1d0134baf707b689700b53bd3066a5a8cfd94b3c9fc8/loguru-0.5.3-py3-none-any.whl (57kB)
    100% |████████████████████████████████| 61kB 1.9MB/s 
Requirement already satisfied: requests[socks] in /usr/lib/python3/dist-packages (from -r requirements.txt (line 7))
Requirement already satisfied: cloudscraper>=1.0 in /usr/local/lib/python3.8/dist-packages (from PixivPy->-r requirements.txt (line 1))
Requirement already satisfied: requests-toolbelt>=0.9.1 in /usr/local/lib/python3.8/dist-packages (from PixivPy->-r requirements.txt (line 1))
Requirement already satisfied: pydantic<2.0.0,>=1.6.1 in /usr/local/lib/python3.8/dist-packages (from graia-application-mirai->-r requirements.txt (line 2))
Requirement already satisfied: yarl<2.0.0,>=1.4.2 in /usr/local/lib/python3.8/dist-packages (from graia-application-mirai->-r requirements.txt (line 2))
Requirement already satisfied: regex<2021.0.0,>=2020.7.14 in /usr/local/lib/python3.8/dist-packages (from graia-application-mirai->-r requirements.txt (line 2))
Requirement already satisfied: graia-broadcast in /usr/local/lib/python3.8/dist-packages (from graia-application-mirai->-r requirements.txt (line 2))
Requirement already satisfied: aiohttp<4.0.0,>=3.6.2 in /usr/local/lib/python3.8/dist-packages (from graia-application-mirai->-r requirements.txt (line 2))
Requirement already satisfied: croniter<0.4.0,>=0.3.34 in /usr/local/lib/python3.8/dist-packages (from graia-application-mirai->-r requirements.txt (line 2))
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.8/dist-packages (from requests[socks]->-r requirements.txt (line 7))
Requirement already satisfied: pyparsing>=2.4.7 in /usr/local/lib/python3.8/dist-packages (from cloudscraper>=1.0->PixivPy->-r requirements.txt (line 1))
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.8/dist-packages (from yarl<2.0.0,>=1.4.2->graia-application-mirai->-r requirements.txt (line 2))
Requirement already satisfied: multidict>=4.0 in /usr/local/lib/python3.8/dist-packages (from yarl<2.0.0,>=1.4.2->graia-application-mirai->-r requirements.txt (line 2))
Requirement already satisfied: iterwrapper<0.2.0,>=0.1.2 in /usr/local/lib/python3.8/dist-packages (from graia-broadcast->graia-application-mirai->-r requirements.txt (line 2))
Requirement already satisfied: chardet<4.0,>=2.0 in /usr/lib/python3/dist-packages (from aiohttp<4.0.0,>=3.6.2->graia-application-mirai->-r requirements.txt (line 2))
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp<4.0.0,>=3.6.2->graia-application-mirai->-r requirements.txt (line 2))
Requirement already satisfied: typing-extensions>=3.6.5 in /usr/local/lib/python3.8/dist-packages (from aiohttp<4.0.0,>=3.6.2->graia-application-mirai->-r requirements.txt (line 2))
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.8/dist-packages (from aiohttp<4.0.0,>=3.6.2->graia-application-mirai->-r requirements.txt (line 2))
Requirement already satisfied: natsort in /usr/local/lib/python3.8/dist-packages (from croniter<0.4.0,>=0.3.34->graia-application-mirai->-r requirements.txt (line 2))
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.8/dist-packages (from croniter<0.4.0,>=0.3.34->graia-application-mirai->-r requirements.txt (line 2))
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.8/dist-packages (from python-dateutil->croniter<0.4.0,>=0.3.34->graia-application-mirai->-r requirements.txt (line 2))
Building wheels for collected packages: aiofiles
  Running setup.py bdist_wheel for aiofiles ... done
  Stored in directory: /root/.cache/pip/wheels/99/b3/81/61b5d666396e0186b8f27a2ca6e922ab613ee6d735af31cc5b
Successfully built aiofiles
Installing collected packages: PixivPy, graia-application-mirai, json5, Pillow, aiofiles, loguru
Successfully installed Pillow-8.0.1 PixivPy-3.5.10 aiofiles-0.6.0 graia-application-mirai-0.10.10 json5-0.9.5 loguru-0.5.3
root@VM-0-12-ubuntu:~/PixivBot/PixivBot-0.2.0# 
root@VM-0-12-ubuntu:~/PixivBot/PixivBot-0.2.0# 
root@VM-0-12-ubuntu:~/PixivBot/PixivBot-0.2.0# python3 bot.py
2020-10-28 18:17:08.512 | INFO     | utils.settings:<module>:38 - Config file was loaded successfully.
Traceback (most recent call last):
  File "bot.py", line 9, in <module>
    from handler import *
  File "/root/PixivBot/PixivBot-0.2.0/handler/__init__.py", line 1, in <module>
    from .pixiv_illust_query_handler import PixivIllustQueryHandler
  File "/root/PixivBot/PixivBot-0.2.0/handler/pixiv_illust_query_handler.py", line 9, in <module>
    from pixiv import make_illust_message, papi, PixivResultError
  File "/root/PixivBot/PixivBot-0.2.0/pixiv/__init__.py", line 3, in <module>
    from .message_maker import make_illust_message
  File "/root/PixivBot/PixivBot-0.2.0/pixiv/message_maker.py", line 6, in <module>
    from graia.template import Template
ModuleNotFoundError: No module named 'graia.template'
root@VM-0-12-ubuntu:~/PixivBot/PixivBot-0.2.0# 


```

**运行环境**

- 操作系统：ubuntu
- mirai-console-1.0-M4.jar  
- mirai-console-pure-1.0-M4.jar  
- mirai-core-qqandroid-1.2.3.jar
- mirai-api-http-v1.8.4.jar

**Comment by ssttkkl** [comment]
忘记更新requirement.txt了……
你手动`pip install graia-template`一下

**Comment by mtuba** [comment]
感谢回复
ModuleNotFoundError: No module named 'graia.template' 报错消失了，但是出现了新的问题...
执行 `python3 bot.py` 后报错 AttributeError: 'ApplicationLaunched' object has no attribute 'app'
```
root@VM-0-12-ubuntu:~/PixivBot/PixivBot-0.2.0# python3 bot.py 
2020-10-28 18:37:37.266 | INFO     | utils.settings:<module>:38 - Config file was loaded successfully.
2020-10-28 18:37:37.823 | INFO     | my_logger:info:7 - initializing app...
Traceback (most recent call last):
  File "bot.py", line 89, in <module>
    app.launch_blocking()
  File "/usr/local/lib/python3.8/dist-packages/graia/application/__init__.py", line 1076, in launch_blocking
    loop.run_until_complete(self.initialize())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/graia/application/__init__.py", line 997, in initialize
    self.broadcast.postEvent(ApplicationLaunched(self))
  File "/usr/local/lib/python3.8/dist-packages/graia/application/event/lifecycle.py", line 9, in __init__
    self.app = app
AttributeError: 'ApplicationLaunched' object has no attribute 'app'
```

这个问题我在参考 GraiaProject/Application 文档 https://graia-document.vercel.app/ 的安装并配置开发环境时，运行 bot.py 也出现了同样的问题
